spring.application.name=blog

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/posts
spring.datasource.username=postgres
spring.datasource.password=postgres

logging.file.name=logs/log.log